name: lint, test, build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.12.1 ]

    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install modules
        run: npm ci

      - name: lint typescript
        run: npm run lint:ts

      - name: lint scss
        run: npm run lint:scss

      - name: build production app
        run: npm run build:prod

      - name: unit tests
        run: npm run test:unit

      - name: build storybook
        run: npm run storybook:build

      - name: screenshot testing
        run: npm run test:loki:ci
